### ISSUE TITLE
Performance Scenario: Basic Views

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4175]
**This is top-level performance scenario for 1.0.0. We're using this item to track the status and all of the individual improvements.**

Code here: https://github.com/aspnet/Performance/tree/dev/testapp/BasicViews
#### Summary

This is a simple browser-based app that accepts a form post, updates a database, and renders validation errors + the same form. This should be naively written, and very similar to a 'Create' view that a developer would generate using scaffolding.
- Conventional routing
- Database (localdb)
- Layout page from project template (script/link taghelpers)
- Startup code from no-auth project template
- View code using taghelpers for form and inputs
# 
#### Variations
- Using TagHelpers (primary) - http://+:5000/
- Using HTML helpers - http://+:5000/Home/HtmlHelpers
# 
#### Status

Scenario Status: **Complete**
- [x] Update Layout Page
- [x] Add database
- [x] Add validation attributes
- [x] Switch default to use taghelpers
- [x] Add antiforgery validation + client

Known Investigations/Improvements:
- [x] https://github.com/dotnet/cli/issues/1736 `CompilationOptions` memory usage
- [ ] https://github.com/aspnet/Mvc/issues/3924 `TagHelper` activation too expensive
- [x] https://github.com/aspnet/Mvc/issues/4244 `RazorPage` activation too expensive
- [x] https://github.com/aspnet/Mvc/issues/4267 Optimize `CoerceResultToTaskAsync`
- [x] https://github.com/aspnet/Mvc/issues/4468 Reduce allocations in Link/Script TagHelper

**Comment by rynowak** [comment]
Some baselines now that we've completed the scenario. All measurements are x64 CoreCLR.


**Allocations - 3001 requests**
![image](https://cloud.githubusercontent.com/assets/1430011/13576018/669667a8-e440-11e5-8d3e-651f694dcf21.png)

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by rynowak** [comment]
Updates here - allocation data

![image](https://cloud.githubusercontent.com/assets/1430011/14510595/113668a8-0187-11e6-85fc-90041a685b71.png)

**Comment by rynowak** [comment]
**Update 5/23**

Allocation Data: 3000 requests
![image](https://cloud.githubusercontent.com/assets/1430011/15488720/0a3a1986-210e-11e6-93a7-b355c30fe446.png)

No really significant changes here, we've made some small improvements in URL generation in routing and some improvements to generated TagHelper view code, but nothing major to report.

Sampling data is hard to summarize here - very little request time is spent doing ASP.NET related concerns, significant amount of time spent in EF.
