### ISSUE TITLE
Performance Scenario: Big ModelBinding

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4179]
**This is top-level performance scenario for RC2. We're using this item to track the status and all of the individual improvements.**

Code here: https://github.com/aspnet/Performance/tree/dev/testapp/BigModelBinding
#### Summary

This is an API app that accepts a form post, updates a database, and renders a view for the updated model data. This is an area of known-badness in MVC and should help us put the cost of modelbinding/validation in context in a full application. This should be naively written, like a line-of-business app that's gotten quite large.
- Conventional routing
- Layout page from project template (script/link taghelpers)
- Startup code from no-auth project template
- View code using taghelpers for displaying the model values
# 
#### Variations

(None)
# 
#### Status

Scenario Status: incomplete
- [ ] Review startup code
- [ ] Add View

Known Investigations/Improvements:
- [x] #4361 - Cache TypeConverters in SimpleTypeModelBinder
- [ ]  #4362 - Carry the current ModelStateEntry on the ModelBindingContext
- [ ]  #4016 - Too much string allocation in Model Binding

**Comment by rynowak** [comment]
Some preliminary data here: 
https://github.com/aspnet/Mvc/pull/4355#issuecomment-202495200
https://github.com/aspnet/Mvc/pull/4355#issuecomment-202500438

Without adding views to this 60-65% of the app's time is spent in GC. I can get 1750 rps on my machine but there are frequent pauses. Filing an initial round of bugs with these data.

**Comment by rynowak** [comment]
**Update 5/23**

Allocation Data: 3000 requests

![image](https://cloud.githubusercontent.com/assets/1430011/15514086/336a2a92-219c-11e6-9ba4-088370d4f758.png)

Main issues here are to do with allocations and are tracked already
