### ISSUE TITLE
[Tracker] MSBuild conversion issues

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5482]
This is just to track all the issues that I've run into so we can capture when they're resolved.

- [x] **Can't run GenerateResource Task.** https://github.com/dotnet/sdk/issues/346.
- [x] **Migrate doesn't respect global.json.** https://github.com/dotnet/cli/issues/4568  / https://github.com/dotnet/cli/issues/4548
- [x] **Migrate does not understand transitive project references that have already been migrated.** https://github.com/dotnet/cli/issues/4591. - By design unless specifying `--skip-backup`
- [x] **Migrate does not include transitive frameworkAssemblies.** https://github.com/dotnet/cli/issues/4595.
- [x] **Migrating dotnet-test-xunit breaks test execution.** https://github.com/dotnet/cli/issues/4629.
- [x] **Cannot add Microsoft.Net.Test.Sdk as a dependency of net451 projects**. https://github.com/Microsoft/vstest/issues/190.
- [x] **dotnet test should have an indication that the project is being built.** https://github.com/Microsoft/vstest/issues/192.
- [x] **Property definition doesn't support CData.** https://github.com/Microsoft/msbuild/issues/1294.
- [x] **Building project with twice (or more) transitive dependencies explodes.** https://github.com/dotnet/sdk/issues/353.
- [x] **dotnet run requires framework to be specified when multiple are present** https://github.com/dotnet/sdk/issues/358.
- [x] **Console.Out does not make its way to test execution output**. https://github.com/Microsoft/vstest/issues/195.
- [x] **ctrl + c doesn't stop test execution** https://github.com/Microsoft/vstest/issues/199.
- [x] **Trying to build projects with project references that target different SDK versions explodes.** https://github.com/dotnet/sdk/issues/352.
- [x] **Custom XUnit test bits aren't used/run by the test runner** https://github.com/Microsoft/vstest/issues/291
- [x] **Test projects sometimes require `<OutputType>Exe</OutputType>`**. https://github.com/Microsoft/vstest/issues/287
- [x] **contentFiles support in nuget generated targets file.** https://github.com/NuGet/Home/issues/3683.
- [x] **Transitive references.** https://github.com/dotnet/roslyn-project-system/issues/199.
- [x] **PackageReference to contentFiles package breaks compilation of 'net45x' tfms** https://github.com/dotnet/sdk/issues/495.
- [x] **dotnet-test may return exit code 0 even if some TFMs fail** https://github.com/Microsoft/vstest/issues/283
- [x] **Cross-targetting apps get wrong version of NETStandard.Library on .NETFramework** https://github.com/dotnet/sdk/issues/614
- [x] **Transitive package framework assembly references don't get included in build.** https://github.com/dotnet/sdk/issues/365.
- [x] **Test projects cannot be both desktop and non-desktop if dependencies changes based on RuntimeIdentifier.** https://github.com/Microsoft/vstest/issues/198.
- [x] **Facades from desktop framework targeting pack are not emitted to .deps.json for PreserveCompilationContext** https://github.com/dotnet/sdk/issues/480.
- [x] **Cannot build web desktop web application without specifying RuntimeIdentifier.** https://github.com/dotnet/sdk/issues/357.
- [x] **TRX logger produces invalid XML file** https://github.com/Microsoft/vstest/issues/320
- [x] **Visual Studio executes tests in the Windows directory (C:\Windows\system32)** https://developercommunity.visualstudio.com/content/problem/7956/current-working-directory-of-net-core-tests-is-set.html. Tracked here: https://github.com/Microsoft/vstest/issues/311
- [x] **Cannot pack a .NET Core CLI tool** https://github.com/NuGet/Home/issues/4321

---------------------------------
Bugs found after re-attempting migrate (In Progress...):
- [x] **Migration: excluded files need to be removed** https://github.com/dotnet/cli/issues/5461
- [x] **dotnet migrate does not handle project.json embed behavior of the compiler/resources folder** https://github.com/dotnet/cli/issues/5477
- [x] **Latest d15rel Visual Studio can't restore cross targeting projects** https://github.com/NuGet/Home/issues/4496
- [x] **Desktop test projects with class fixtures can fail to find tests.** https://github.com/Microsoft/vstest/issues/408
- [x] **runtimeconfig.json contains incorrect framework version** https://github.com/dotnet/sdk/issues/686
- [x] **xunit.runner.visualstudio cannot be used with MVC in test projects unless you add a reference to Microsoft.DotNet.InternalAbstractions.** https://github.com/xunit/xunit/issues/1088
- [x] **Transitive references do not show all the time in the Dependency node** https://github.com/dotnet/roslyn-project-system/issues/1423
- [ ] **dotnet restore does not capture transitive framework assemblies from project references** https://github.com/NuGet/Home/issues/4412
- [ ] **allow dotnet pack to pack nuspec file without needing a csproj file** https://github.com/NuGet/Home/issues/4254
- [ ] **dotnet migrate should fail to migrate projects that have "shared" properties in their project.json.** ~~https://github.com/dotnet/cli/issues/5407~~, https://github.com/dotnet/cli/issues/5318
- [ ] **DependencyContext cannot load entry assembly when used in a net46 test.** https://github.com/Microsoft/vstest/issues/196.
- [ ] **Overloaded test methods result in InvalidOperationException** https://github.com/Microsoft/vstest/issues/392
- [x] **Solution with 56 projects is unsable once migrated to csproj.** https://github.com/dotnet/roslyn-project-system/issues/1384
- [ ] **AppDomain.CreateDomain cannot dynamically load test assembly** Microsoft/vstest#419
- [x] **Running tests that depend on string[] TypeDescriptor converters fail.** Microsoft/vstest#427
- [ ] **corfxlab repro has some issues with Solution Open and Restore.** NuGet/Home#4617
- [ ] **Auto-restore fails multiple times until all projects are loaded** NuGet/Home#4577
- [ ] **"Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number" opening MVC/CLI repros** NuGet/Home#4626
- [ ] **SkipCompilerExecution Error** ~~dotnet/roslyn-project-system#1554~~, Microsoft/msbuild#1726
- [ ] **Project fault opening the MVC solution stating "Some data sources have regressed in their version number"** dotnet/roslyn-project-system#1573
- [ ] **NuGet background restore waits until VS has focus** NuGet/Home#4623
- [ ] **Packing csproj with long description issues unresolvable warning about missing summary text** nuget/home#4587
- [ ] **Long test data results in `Contents of string '{test name}' exceeds max of '449', string has been truncated.` messages** xunit/xunit#1139
- [ ] **SIGINT leaves dotnet processes running incorrectly. Causes problems on subsequent builds/runs.** dotnet/cli#4856 and related **`dotnet run` doesn't handle ctrl-c well** dotnet/cli#812
  - not specific to MVC or even large repos
- [ ] **`dotnet msbuild` commands hang with some command-line redirections** ~~dotnet/cli#5849~~
  - now **`dotnet msbuild` commands sometimes hang after writing MSBuild_*.failure.txt files** Microsoft/msbuild#1808
- [ ] **Multitfm support for IDE (.net core)** Microsoft/vstest#298
  - for MVC, this means only .NET Core tests run in Visual Studio
- [ ] **MSB3270 warnings for .NET Framework test project that depends on an ASP.NET Core web site** dotnet/sdk#926
- [ ] **Binding Redirects necessary to run Unit Tests on .NET Framework are not preserved when running in `testhost`** Microsoft/vstest#428
  - **Re-enable functional tests on full .NET Framework** #5873 is a dupe / symptom of this

**Comment by piotrpMSFT** [comment]
@srivatsn this is an interesting issue for us to track...

**Comment by NTaylorMullen** [comment]
Status:
- Migrated MVC src projects with work arounds.
- Migrated MVC sample project with work arounds.
- Migrated 1.5 MVC test projects but stopped due to the time spent working around known issues.

All issues found are listed above. Will continue migrating test projects when the vstest migration issues have been resolved.

**Comment by NTaylorMullen** [comment]
Adding this guy: https://github.com/dotnet/sdk/issues/111- **Add .deps.json file for desktop web apps when PreserveCompilationContext = true**

Essentially `preserveCompilationContext = true` doesn't always work so any semi-advanced View will explode at runtime if run on the desktop framework. /cc @Eilon for visibility

**Comment by natemcmaster** [comment]
Here's another one to add: https://github.com/dotnet/sdk/issues/495  **PackageReference to contentFiles package breaks compilation of 'net45x' tfms**

**Comment by natemcmaster** [comment]
It may be interesting to also track the CLI teams own attempts to migrate this repo: https://github.com/dotnet/cli/issues/5378

**Comment by dtivel** [comment]
Hey, @rrelyea, please check out the NuGet issues above.

**Comment by dougbu** [comment]
This doesn't exactly block our migration but NuGet/Home#4689, **.csproj file not updated in Visual Studio until user does a Save All or closes solution** will certainly cause developer confusion going forward. We often flip back and forth between command line and Visual Studio.

**Comment by Eilon** [comment]
@NTaylorMullen I guess we can close this right??

**Comment by NTaylorMullen** [comment]
@Eilon I'd say ya. There's still some open issues above but those are tracked elsewhere.
