### ISSUE TITLE
Big Rock: Filters for Razor Pages

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6070]
Pages should use basically the same filter types as controllers, but should expose some unique functionality in place of action filters. In general a pages developer will want to accomplish the same kinds of things with filters as a controller/action developer.

This includes:
- authorization (authZ filters)
- middleware-like behavior (resource filters)
- scoped exception handling (exception filters)
- decorating the execution of results (result filters)
- manipulating action arguments (action filters)

We'll want to provide a little something extra for pages, likely to do with manipulating handler methods 👍 

There's a lot more to do here, because designing a new filter type, we need to decide how filters get configured when you have a mix of pages/page-models/handler-methods/application-model.

Related items:
 - [x] https://github.com/aspnet/Mvc/issues/5979 Add a filter provider for TempDataAttribute to RazorPages
 - [x] https://github.com/aspnet/Mvc/issues/6124 Support Filters for RazorPages
 - [x] https://github.com/aspnet/Mvc/issues/6331 Add a new filter type for pages
 - [x] https://github.com/aspnet/Mvc/issues/6332 Add logging and diagnostic source for page handlers
 - [x] https://github.com/aspnet/Mvc/issues/6333 Improve unit tests for PageActionInvoker
 - [ ] https://github.com/aspnet/Mvc/issues/6334 Rationalize filters as attributes with Pages

**Comment by rynowak** [comment]
Everything in this list is done or in PR, so closing this issue.

**Comment by sketchpunk** [comment]
Is there an example of how to use this? I was using RazorPagesOptions.AuthorizeFolder for force authorization on pages but now thats not supported in the final release. Thanks.

**Comment by pranavkm** [comment]
@sketchpunk we moved the methods to hang off `RazorPagesOptions.Conventions`. You should be able able to `options.Conventions.AuthorizeFolder(..)`. Additionally, applying the `Authorize` on page model is also supported now.

**Comment by sketchpunk** [comment]
@pranavkm thanks man, been looking all day and couldn't find where the methods moved to or what replaced them.  Just one more question, I dont use a page model, but I do use the inline model. I added "using Microsoft.AspNetCore.Authorization" to my razor page and tried putting Authorize  on OnGet but it doesn't do anything but it compiles just fine. Not sure if even meant to work in the inline model. Thanks for your help.

**Comment by pranavkm** [comment]
@sketchpunk the attribute has to be on a type not on handler methods. For instance https://github.com/aspnet/Mvc/blob/dev/test/WebSites/RazorPagesWebSite/ModelWithAuthFilter.cs#L10.
