### ISSUE TITLE
Big Rock: Pages/PageModel API surface area

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6071]
Related issues:

- [x] Add IActionResults factory methods to Page and PageModel https://github.com/aspnet/Mvc/issues/5846
- [x] Can we make TryUpdateModel better for "page as view model" scenario https://github.com/aspnet/Mvc/issues/5938
- [x] Add LocalRedirect to Page/PageModel #6087

**Comment by rynowak** [comment]
### Appendix A:

APIs and where they show up - these are the notes that will feed into our decisions about what to put where.
```
IHtmlHelper<TModel> Html (@inject)
    IJsonHelper Json (@inject)
    IViewComponentHelper Component (@inject)
    IUrlHelper Url (@inject)
    IModelExpressionProvider ModelExpressionProvider (@inject)
```

**Comment by rynowak** [comment]
### Appendix B: Flattening Layers

Here are the notes about what's available in each of our high level targets:
```
Controller:
    VDD ViewData
    ITempDataDictionary  TempData
    dynamic ViewBag
    
ControllerBase:
    HttpContext HttpContext
    HttpRequest Request
    HttpResponse Response
    RouteData RouteData
    ModelStateDictionary ModelState
    ControllerContext ControllerContext
    IModelMetadataProvider MetadataProvider
    IModelBinderFactory ModelBinderFactory
    IUrlHelper Url
    IObjectModelValidator ObjectValidator
    ClaimsPrincipal User
    TryUpdateModelAsync(...)
    TryValidateModel(...)
    
RazorPageBase:
    ViewContext ViewContext
    dynamic ViewBag
    ClaimsPrincipal User
    
RazorPage:
    HttpContext Context
    
RazorPageOfT:
    TModel Model
    ViewDataDictionary<TModel> ViewData
    IHtmlHelper<TModel> Html (@inject)
    IJsonHelper Json (@inject)
    IViewComponentHelper Component (@inject)
    IUrlHelper Url (@inject)
    IModelExpressionProvider ModelExpressionProvider (@inject)
    
Page:
    ViewContext ViewContext
    HttpContext HttpContext
    HttpRequest Request
    HttpResponse Response
    PageArgumentBinder Binder
    ModelStateDictionary ModelState
    IHtmlHelper<TModel> Html (@inject)
    IJsonHelper Json (@inject)
    IViewComponentHelper Component (@inject)
    IUrlHelper Url (@inject)
    IModelExpressionProvider ModelExpressionProvider (@inject)
    
PageModel:
    PageArgumentBinder Binder
    IUrlHelper Url
    Page Page
    PageContext PageContext
    ViewContext ViewContext
    HttpContext HttpContext
    HttpRequest Request
    HttpResponse Response
    ModelStateDictionary ModelState
    ITempDataDictionary TempData
    ViewDataDictionary ViewData
    BindAsync<TModel>(...)
    TryUpdateModelAsync(...)
```

**Comment by rynowak** [comment]
### Appendix C: What should change?

Here are notes about what to change:
```
Controller:
    ViewDataDictionary ViewData
    ITempDataDictionary  TempData
    dynamic ViewBag
    HttpContext HttpContext
    HttpRequest Request
    HttpResponse Response
    RouteData RouteData
    ModelStateDictionary ModelState
    ControllerContext ControllerContext
    IModelMetadataProvider MetadataProvider
    IModelBinderFactory ModelBinderFactory
    IUrlHelper Url
    IObjectModelValidator ObjectValidator
    ClaimsPrincipal User
    TryUpdateModelAsync(...)
    TryValidateModel(...)
    
RazorPageOfT:
    HttpContext Context
    ViewContext ViewContext
    dynamic ViewBag
    ClaimsPrincipal User
    TModel Model
    ViewDataDictionary<TModel> ViewData
    IHtmlHelper<TModel> Html (@inject)
    IJsonHelper Json (@inject)
    IViewComponentHelper Component (@inject)
    IUrlHelper Url (@inject)
    IModelExpressionProvider ModelExpressionProvider (@inject)
    
Page:

REMOVE PageArgumentBinder
ADD RouteData RouteData
ADD IModelMetadataProvider MetadataProvider
ADD IModelBinderFactory ModelBinderFactory
ADD IObjectModelValidator ObjectValidator
ADD TryUpdateModelAsync(...)
ADD TryValidateModel(...)

    ViewContext ViewContext
    dynamic ViewBag
    ClaimsPrincipal User
    HttpContext HttpContext
    HttpRequest Request
    HttpResponse Response
    ModelStateDictionary ModelState
    IHtmlHelper<TModel> Html (@inject)
    IJsonHelper Json (@inject)
    IViewComponentHelper Component (@inject)
    IUrlHelper Url (@inject)
    IModelExpressionProvider ModelExpressionProvider (@inject)
    
PageModel:
REMOVE PageArgumentBinder
ADD RouteData RouteData
ADD IModelMetadataProvider MetadataProvider
ADD IModelBinderFactory ModelBinderFactory
ADD IObjectModelValidator ObjectValidator
ADD TryUpdateModelAsync(...) (review overloads)
ADD TryValidateModel(...)
ADD dynamic ViewBag

    PageArgumentBinder Binder
    IUrlHelper Url
    Page Page
    PageContext PageContext
    ViewContext ViewContext
    HttpContext HttpContext
    HttpRequest Request
    HttpResponse Response
    ModelStateDictionary ModelState
    ITempDataDictionary TempData
    ViewDataDictionary ViewData
    BindAsync<TModel>(...)
    TryUpdateModelAsync(...)
```

**Comment by DamianEdwards** [comment]
Hmm, I kinda don't want to add `ViewBag`. That thing isn't particularly nice and I wouldn't consider it idiomatic for Pages.

**Comment by pranavkm** [comment]
@rynowak - do you want this work item open? Looks like the issues here are already covered.
