### ISSUE TITLE
Big Rock: Handler Methods

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6072]
Related issues:

- [ ] Add ability to change Razor Pages page handler method naming convention via ApplicationModel #6065 
- [x] FormAction should be eligible to come from any value provider #6081
- [x] Revisit conventions for naming of handler methods #6090
- [x] Create a new attribute for Pages property binding #6091

-----------------------------------------------

## Summary

We want Pages to have a place to put *code* that can be used to take over control flow before a Page is rendered. While you can put initialization code directly in a Page, this isn't a good way to do control flow. Additionally we want to leverage the kinds of things MVC users are already familiar with for input processing (parameters and properties). This leads us to an instance method, the **Handler Method** as a way to run code before the Page starts rendering.

Pages have Handler Methods to support two primary use cases:
- Allow the Page to run initialization code before the rendering of the HTML
- Process form submissions, which usually involves a redirect, or showing the same Page with the same model (validation errors)

These cases aren't always distinct, they just tell us what to optimize for in each case. If we build a set of strong primitives, then mixing them is straightforward. 

Think of the typical MVC `Create` actions (or any other CRUD flow) as a motivating example. In general when a page is first going to render, it won't need to handle validation errors. In general when a page needs to process a form submission, it doesn't need to 'get' the model from the database first.

Given how different these usages are, we want some kind of system where there are multiple Handler Methods per-page. This will feel very MVC like, and give you a place to put the code for each task.

### Usages in CRUD cases

When visiting a Page for a CRUD form, the Handler Method needs to initialize all of the state needed to render HTML (getting data from database, initializing computed properties). Model binding can be used here but its use is somewhat limited, and is generally limited to finding the database model. By construction, this usage of a handler method results in rendering the Page's output as HTML except in error cases, which use an action result to change control flow. Generally in this case the verb is a `GET`, but the functionality that will be implemented here is also agnostic of the verb to a large degree. 

The pseudocode for such a method would look something like:
```
public async Task HandlerMethod(int id)
{
    Customer = await Db.Customers.FindByIdAsync(id);
}
```
OR
```
public async Task<IActionResult> HandlerMethod(int id)
{
    Customer = await Db.Customers.FindByIdAsync(id);
    if (Customer == null)
    {
        return NotFound();
    }
    
    return Page();
}
```

Which shape to choose depends on whether or not you want to handle 'Not Found' inside the Page or if you want to use a global 'Not Found' Page.

---------------------------------

To process a form submission, the handler method first does model binding and validation to see if the updated model has satisfied all requirements. Then if the model is valid the Handler Method will usually redirect to another Page to display the results. If the model is invalid, the Page will usually render its HTML again, this time including the values provided by the user in the form submission along with any validation errors. It's import here to optimize for ease of use with model binding and control flow with action results.

Typical pseudocode would look like:

```
public async Task<IActionResult> HandlerMethod()
{
    if (ModelState.IsValid)
    {
        Db.Customers.Update(Customer);
        await Db.SaveChangesAsync();
        return RedirectToPage();
    }
    
    return Page();
}
```

Note that model binding here is taking place on a property `Customer`, not on a parameter. This is much more idiomatic, and the state needed for the Page to render its HTML is already initialized before we get into the Handler Method.

#### Conclusions

From looking at the CRUD case we can validate that some of the assumptions we discussed up front are working, and add a few additional requirements:
- Model binding to properties is the simplest and most idiomatic choice
- We should not do model binding to properties by default for `GET` requests to avoid validation errors that aren't meaningful
- Separate handlers for 'show the form' and 'process the data' are necessary
- The existing set of primitives plus our new 'model bind, but not on `GET`' primitive are flexible enough to build almost anything

### Dispatching

Given all of the above, we need to decide on what the conventions are for Handler Methods and what the rules are for dispatching to them.So far we basically have the requirement for dispatching between 'show the form' and 'process the input' but this can be satisfied in a number of ways.

Here's a proposal:

Handler methods are defined by-name using the convention `On[Verb][Handler?]Async`. The `On` prefix and `Async` suffix are optional in all cases, so `OnGetFooAsync` and `GetFoo` are equivalent. The handler is also optional, but meaningful. We will determine what's considered a verb and not by looking at casing. 

So these are some valid handler names:
- `Get`
- `Post`
- `OnGet`
- `OnGetAsync`
- `GetAsync`
- `GetResults`
- `OnPostEditAsync`

We'll support all verbs, including arbitrary/nonsense verbs.

The `handler` can come from a variety of sources including the route data, form, and query string. We'll later make this set configurable.

For selection, a handler method must match the verb, and if the handler method has a `handler` name it must match as well. A handler method with a matching `handler` name is considered a better match than one without.

**Comment by rynowak** [comment]
297196baa0d4a28a4f71d0b4bba2d5b942af6190
